CREATE TABLE DATA (
  _id                 INTEGER PRIMARY KEY NOT NULL,
  CREATION_TIME_UTC   INTEGER DEFAULT (CAST((JULIANDAY('now') - 2440587.5) * 86400000 AS INTEGER)) NOT NULL,
  LAST_WRITE_TIME_UTC INTEGER DEFAULT (CAST((JULIANDAY('now') - 2440587.5) * 86400000 AS INTEGER)) NOT NULL,
  CONTENT             TEXT
);

CREATE VIRTUAL TABLE CONTENT USING fts4(content = "DATA", CONTENT);

CREATE TRIGGER AFTER UPDATE ON DATA
  WHEN old.LAST_WRITE_TIME_UTC = new.LAST_WRITE_TIME_UTC
BEGIN
  UPDATE DATA
  SET LAST_WRITE_TIME_UTC = CAST((JULIANDAY('now') - 2440587.5) * 86400000 AS INTEGER) where _id=old._id;
END;

CREATE TRIGGER BEFORE UPDATE ON DATA BEGIN
  DELETE FROM CONTENT
  WHERE rowid = old.rowid;
END;
CREATE TRIGGER BEFORE DELETE ON DATA BEGIN
  DELETE FROM CONTENT
  WHERE rowid = old.rowid;
END;

CREATE TRIGGER AFTER UPDATE ON DATA BEGIN
  INSERT INTO CONTENT (rowid, CONTENT) VALUES (new.rowid, new.CONTENT);
END;
CREATE TRIGGER AFTER INSERT ON DATA BEGIN
  INSERT INTO CONTENT (rowid, CONTENT) VALUES (new.rowid, new.CONTENT);
END;


SELECT
  _id,
  DATETIME(CREATION_TIME_UTC / 1000, 'unixepoch', 'localtime'),
  DATETIME(LAST_WRITE_TIME_UTC / 1000, 'unixepoch', 'localtime') AS LAST_WRITE_TIME_UTC,
  CONTENT
FROM DATA
ORDER BY LAST_WRITE_TIME_UTC
  DESC;

SELECT *
FROM DATA
ORDER BY LAST_WRITE_TIME_UTC
  DESC;

SELECT *
FROM DATA
WHERE _id = ?
LIMIT 1;

SELECT
  DATETIME(CREATION_TIME_UTC / 1000, 'unixepoch', 'localtime'),
  DATETIME(LAST_WRITE_TIME_UTC / 1000, 'unixepoch', 'localtime') AS LAST_WRITE_TIME_UTC,
  CONTENT
FROM DATA
WHERE _id = ?
LIMIT 1;

SELECT CONTENT
FROM DATA
WHERE _id = ?
LIMIT 1;

INSERT INTO DATA (CONTENT)
VALUES (?);

INSERT INTO DATA (CREATION_TIME_UTC, LAST_WRITE_TIME_UTC, CONTENT)
VALUES (?, ?, ?);

UPDATE DATA
SET CONTENT = ?
WHERE _id = ?;

DELETE FROM DATA
WHERE _id = ?;

DROP TABLE DATA;
